#!/usr/bin/env python3
import argparse
from datetime import datetime
import os
from pathlib import Path
import signal
import subprocess
import sys
import yaml


def find_config_file(start_path: Path) -> Path:
    """Search up directory tree for .howdone.yaml file"""
    current_path = start_path.resolve()
    while current_path != current_path.parent:
        config_candidate = current_path / ".howdone.yaml"
        if config_candidate.exists():
            return config_candidate
        current_path = current_path.parent
    return None


def load_config(config_file: Path) -> dict:
    """Load configuration from YAML file"""
    with open(config_file, "r") as f:
        return yaml.safe_load(f)


def format_command_line(command):
    """Format a command for display. This flattens commands which are already separated into arguments."""
    if isinstance(command, str):
        return command
    else:
        return " ".join(command)


def log_message(msg, *args, **kwargs):
    print("[howdone] " + msg, *args, **kwargs)


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""
Run a command and capture its output along with provenance information to a directory.

All the commands are run with stdout and stderr combined to keep them aligned even with large buffer sizes (which can
occur when processes are outputing to pipes).

The configuration file is as follows:

# A prefix applied to the autogenerated name of output directories
name_prefix: run
# The file to place the output of the command in
output_file: output.txt
# The name of the environment variable which is set to the output directory
output_dir_var: OUTPUT_DIR
# A map of filenames to the command which will be executed to fill them. 
# Each file will have the command as the first line and then it's output.
commands:
  dirty.diff: git diff --stat HEAD
  git-status.txt: git status
  uname-all.txt: uname --all
  lscpu.txt: lscpu

The generated directory contains the files specified in the configutation and a file `meta.yaml` containing:

run_name: <run name, if any, from command line>
current_directory: <absolute path of the current directory>
date: <date and time in ISO 2026-06-05T20:50:12>
full_command: <full command line of howdone>
meta_config:
    <the configutation read for howdone>
""",
    )
    parser.add_argument(
        "-c",
        "--config",
        type=Path,
        help="""
        Provide a configuration file. If not provided, this will search upward from the current directory for a file
        named `.howdone.yaml`.
        """,
    )
    parser.add_argument(
        "-n", "--name", type=str, help="Provide a name for the run"
    )
    parser.add_argument("-d", "--dir", type=Path, help="Output to the given directory")

    parser.add_argument(
        "cmd",
        nargs="+",
        help="""
        The command to run. If this is a single argument it is passed to a shell as a command (as if it were passed to
        `sh -c 'cmd'`), otherwise the arguments passed through to the subprocess directly bypassing the shell.
        """,
    )
    args = parser.parse_args()

    # Find config file if not provided
    if args.config is None:
        args.config = find_config_file(Path.cwd())
        if args.config is None:
            print(
                "Error: Could not find .howdone.yaml configuration file",
                file=sys.stderr,
            )
            return 1

    # Load configuration
    config = load_config(args.config)

    output_dir: Path
    # Determine output directory
    if args.dir:
        output_dir = args.dir
    else:
        timestamp = datetime.now().strftime("%Y%m%d-%H%M")
        output_dir = Path.cwd() / (config.get("name_prefix", "run") + f"-{timestamp}")

    if output_dir.exists():
        print(
            f"Error: Refusing to write over existing directory: {output_dir}",
            file=sys.stderr,
        )
        return 2
    output_dir.mkdir(parents=True, exist_ok=False)
    print(f"Output directory: {output_dir}")

    meta_data = {
        "run_name": args.name,
        "current_directory": str(Path.cwd().resolve()),
        "date": datetime.now().isoformat(),
        "full_command": " ".join(sys.argv),
        "meta_config": config,
    }

    # Save metadata
    meta_file = output_dir / "meta.yaml"
    with open(meta_file, "w") as f:
        yaml.dump(meta_data, f)

    commands_to_run = list((name, cmd, False) for name, cmd in config.get("commands", {}).items())

    main_command = args.cmd
    # if the main command is a single element then unwrap it, so that it is run in a full shell.
    if len(main_command) == 1:
        main_command = main_command[0]

    commands_to_run.append((config.get("output_file", "output.txt"), main_command, True))

    environ = dict(os.environ)
    environ[config.get("output_dir_var", "OUTPUT_DIR")] = str(output_dir)
    print(environ)

    for filename, command, should_output in commands_to_run:
        log_message(
            f"Running (output to {filename}): {format_command_line(command)}"
        )
        if isinstance(command, str):
            command_args = dict(args=command, shell=True)
        else:
            command_args = dict(args=command, shell=False)
        process = subprocess.Popen(
            **command_args,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=environ,
        )

        output_file = output_dir / filename
        with open(output_file, "w") as f:
            try:
                f.write(f"{format_command_line(command)}\n\n")
                for line in process.stdout:
                    if should_output:
                        print(line, end="", flush=False)
                    f.write(line)
                    f.flush()
            except KeyboardInterrupt:
                # Pass SIGINT on to the child.
                process.send_signal(signal.SIGINT)

            code = process.wait()
            if code != 0:
                log_message(
                    f"Command failed with code {code} (command was {format_command_line(command)})"
                )
                f.write(f"\nCommand failed with code {code}")



if __name__ == "__main__":
    sys.exit(main())
