#!/usr/bin/env python3
import argparse
import os
import signal
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import yaml


@dataclass
class CommandConfig:
    filename: str
    command: str | list
    is_main: bool


DEFAULT_CONFIG = {
    "prefix": "run",
    "output_file": "output.txt",
    "output_dir": {"var": "OUTPUT_DIR"},
    "commands": {},
}


def find_config_file(start_path: Path) -> Path | None:
    """Search up directory tree for .howdone.yaml file"""
    current_path = start_path.resolve()
    while current_path != current_path.parent:
        config_candidate = current_path / ".howdone.yaml"
        if config_candidate.exists():
            return config_candidate
        current_path = current_path.parent
    return None


def load_config(config_file: Path) -> dict:
    """Load configuration from YAML file"""
    with open(config_file, "r") as f:
        return yaml.safe_load(f)


def validate_output_dir_config(config: dict) -> None:
    od = config.get("output_dir", {})
    if not isinstance(od, dict):
        print("Error: 'output_dir' must be a mapping", file=sys.stderr)
        sys.exit(1)
    if "arg" in od:
        arg = od["arg"]
        if isinstance(arg, str):
            args_list = [arg]
        elif isinstance(arg, list):
            args_list = arg
        else:
            raise ValueError("output_dir.arg must be a string or list")
        if not any("<OUTPUT_DIR>" in item for item in args_list):
            raise ValueError("output_dir.arg must contain <OUTPUT_DIR> in at least one item")


def substitute_output_dir(s: str, output_dir: Path) -> str:
    return s.replace("<OUTPUT_DIR>", str(output_dir))


def append_output_dir_arg(command: list | str, raw_arg: list | str, output_dir: Path):
    if isinstance(command, str) and isinstance(raw_arg, str):
        return command + " " + substitute_output_dir(raw_arg, output_dir)
    elif isinstance(command, str) and isinstance(raw_arg, list):
        joined = " ".join(substitute_output_dir(a, output_dir) for a in raw_arg)
        return command + " " + joined
    elif isinstance(command, list) and isinstance(raw_arg, str):
        extra = [substitute_output_dir(x, output_dir) for x in raw_arg.split()]
        return command + extra
    elif isinstance(command, list) and isinstance(raw_arg, list):
        return command + [substitute_output_dir(a, output_dir) for a in raw_arg]
    else:
        raise ValueError("command and raw_arg must be list or str")


def format_command_line(command):
    """Format a command for display. This flattens commands which are already separated into arguments."""
    if isinstance(command, str):
        return command
    else:
        return " ".join(command)


def log_message(msg, *args, **kwargs):
    print("[howdone] " + msg, *args, **kwargs)


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""
Run a command and capture its output, along with provenance information, to a directory.

The provenance information is based on a configuration file that specifies the commands to run. The output of each
command is captured and stored in the output directory. All the commands are run with stdout and stderr combined to keep
them aligned. Each output file begins with the command that generated it.

The configuration file is as follows:

# A prefix applied to the autogenerated name of output directories
prefix: run
# The file for the output of the main command
output_file: output.txt
# How the output directory is communicated to commands. Any or all sub-options may be set:
#   var: set the named environment variable for all commands
#   arg: append argument(s) with <OUTPUT_DIR> substituted to the main command only (string or list)
#   cd: run all commands with cwd set to the output directory
output_dir:
  var: OUTPUT_DIR
# A map of filenames to the commands which will be executed to fill them.
commands:
  dirty.diff: git diff --stat HEAD
  git-status.txt: git status
  uname-all.txt: uname --all
  lscpu.txt: lscpu

The generated directory contains the files specified in the configuration and a file `meta.yaml` containing:

run_name: <run name, if any, from command line>
current_directory: <absolute path of the current directory when running all the commands>
date: <date and time in ISO format, e.g. 2026-06-05T20:50:12>
full_command: <full command line of the howdone invocation>
meta_config:
    <the configuration used by howdone>
""",
    )
    parser.add_argument(
        "-c",
        "--config",
        type=Path,
        help="""
        Provide a configuration file. If not provided, this will search upward from the current directory for a file
        named `.howdone.yaml`.
        """,
    )
    parser.add_argument("-n", "--name", type=str, help="Provide a name for the run")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-d", "--dir", type=Path, help="Output to the given directory")
    group.add_argument(
        "-p",
        "--prefix",
        type=str,
        help="Prefix for the output directory name. This overrides the prefix in the config file.",
    )

    parser.add_argument(
        "cmd",
        nargs="+",
        help="""
        The command to run. If this is a single argument it is passed to a shell as a command (as if it were passed to
        sh -c 'cmd'), otherwise the arguments passed through to the subprocess directly, bypassing the shell.
        """,
    )
    args = parser.parse_args()

    # Find config file if not provided
    config_filename: Path | None = args.config
    if config_filename is None:
        config_filename = find_config_file(Path.cwd())
    if config_filename is None:
        print(
            "Error: Could not find .howdone.yaml configuration file",
            file=sys.stderr,
        )
        return 1

    # Load configuration
    config = {**DEFAULT_CONFIG, **load_config(config_filename)}
    try:
        validate_output_dir_config(config)
    except ValueError as e:
        print(f"Error: Invalid configuration: {e}", file=sys.stderr)
        return 1
    output_dir_config = config["output_dir"]

    output_dir: Path
    # Determine output directory
    if args.dir:
        output_dir = args.dir
    else:
        prefix = args.prefix or config["prefix"]
        timestamp = datetime.now().strftime("%Y%m%d-%H%M")
        output_dir = Path.cwd() / (f"{prefix}-{timestamp}")

    if output_dir.exists():
        print(
            f"Error: Refusing to write over existing directory: {output_dir}",
            file=sys.stderr,
        )
        return 2
    output_dir.mkdir(parents=True, exist_ok=False)
    print(f"Output directory: {output_dir}")

    meta_data = {
        "run_name": args.name,
        "current_directory": str(Path.cwd().resolve()),
        "date": datetime.now().isoformat(),
        "full_command": " ".join(sys.argv),
        "meta_config": config_filename,
    }

    # Save metadata
    meta_file = output_dir / "meta.yaml"
    with open(meta_file, "w") as f:
        yaml.dump(meta_data, f)

    commands_to_run = [
        CommandConfig(filename=name, command=cmd, is_main=False)
        for name, cmd in config["commands"].items()
    ]

    main_command = args.cmd
    # if the main command is a single element then unwrap it, so that it is run in a full shell.
    if len(main_command) == 1:
        main_command = main_command[0]

    if "arg" in output_dir_config:
        main_command = append_output_dir_arg(main_command, output_dir_config["arg"], output_dir)

    commands_to_run.append(
        CommandConfig(filename=config["output_file"], command=main_command, is_main=True)
    )

    environ = dict(os.environ)
    if "var" in output_dir_config:
        environ[output_dir_config["var"]] = str(output_dir)

    for cfg in commands_to_run:
        log_message(
            f"Running (output to {cfg.filename}): {format_command_line(cfg.command)}"
        )
        if isinstance(cfg.command, str):
            command_args = dict(args=cfg.command, shell=True)
        else:
            command_args = dict(args=cfg.command, shell=False)
        cwd = str(output_dir) if output_dir_config.get("cd") else None
        process = subprocess.Popen(
            **command_args,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=environ,
            cwd=cwd,
        )

        output_file = output_dir / cfg.filename
        with open(output_file, "w") as f:
            f.write(f"{format_command_line(cfg.command)}\n\n")
            for line in process.stdout:
                try:
                    if cfg.is_main:
                        print(line, end="", flush=False)
                    f.write(line)
                    f.flush()
                except KeyboardInterrupt:
                    # Pass SIGINT on to the child.
                    process.send_signal(signal.SIGINT)

            code = process.wait()
            if code != 0:
                log_message(
                    f"Command failed with code {code} (command was {format_command_line(cfg.command)})"
                )
                f.write(f"\nCommand failed with code {code}")


if __name__ == "__main__":
    sys.exit(main())
